# Generated by Django 2.1.2 on 2018-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(through='post.PostTag', to='post.Post'),
        ),
    ]
